---

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  DisplayCopNames: true
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3